chore: change output format to es6 "module"
It should be "module" same as it declared in package.json "type" property. After this fix I can use this package without error 

SyntaxError: The requested module 'google-sheet-languages-model' does not provide an export named 'GoogleSheetLanguagesModel'